
name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      node-version: 18.x

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
#    - run: npm test
    - name: Store static website files
      uses: actions/upload-artifact@v3
      with:
        name: static-files
        path: ./public/
        retention-days: 1

  upload_to_artifactory:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download static website files
      uses: actions/download-artifact@v3
      with:
        name: static-files
        path: ./public/
    - run: cd public && zip -r ../public.zip * && cd ..
    - run: curl -u${{ secrets.BOGOLYANDRAS_GENERIC_ARTIFACTORY_USERNAME }}:${{ secrets.BOGOLYANDRAS_GENERIC_ARTIFACTORY_TOKEN }} -T public.zip "https://bogolyandras.jfrog.io/artifactory/default-generic-local/personal-website-gatsby/$BRANCH_NAME.zip"
